# -*- coding: utf-8 -*-
"""RAG_projo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tG1ExG-SIbm0WOeBpJWzxNMU_p-IqSB
"""

# Install dependencies
!pip install -q langchain langchain-community faiss-cpu sentence-transformers pypdf

!pip install -q langchain-groq

from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.chains import RetrievalQA
from langchain_groq import ChatGroq
import os

# Load the Constitution PDF
pdf_path = "/content/The_Constitution_of_Kenya_2010.pdf"
loader = PyPDFLoader(pdf_path)
documents = loader.load()

#  Split into chunks
splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
docs = splitter.split_documents(documents)

#  Create free embeddings (using MiniLM)
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

#  Store in FAISS vector database
vectorstore = FAISS.from_documents(docs, embeddings)

os.environ["GROQ_API_KEY"] = "my_api_key"

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0,
    api_key=os.environ["GROQ_API_KEY"]
)

#  Build RAG pipeline
qa = RetrievalQA.from_chain_type(
    llm=llm,#uses Groq’s LLM to combine the chunks + user query into a final answer.
    retriever=vectorstore.as_retriever(search_kwargs={"k":3}),#pulls the top 3 relevant Constitution chunks.
    chain_type="stuff"
)

#  Test it
query = "What does the Constitution say about the right to life?"
answer = qa.run(query)
print("Q:", query)
print("A:", answer)

# Install Gradio if not already installed
!pip install gradio

import gradio as gr

# Define chatbot function
def chat_with_constitution(user_input, history=[]):
    try:
        answer = qa.run(user_input)   # qa is your RAG RetrievalQA chain
    except Exception as e:
        answer = f"Error: {e}"
    return answer

# Create a Gradio ChatInterface
iface = gr.ChatInterface(
    fn=chat_with_constitution,
    title=" Chat with the Constitution of Kenya",
    description="Ask questions about the Constitution of Kenya (2010).",
    theme="soft"
)

# Launch app
iface.launch(share=True)